script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: UerB4wAmSeUjYJYe7Hd1QgX3PursYHgT8fN6J8P4o7q2Oq53TxHtyh8JOnbqIUwfpoFOJFZgliQgfFf5ukV4+i8/Kpm8Aum/fjroGB6ZV6Hb6tndIhfWvMd2FZcbRs/LBiixULvlPEv+c5l/5+Qfma2cZbT1uLvYBCxFwNj2mjU=
  app: anbu-presentation-stub01
  on:
    repo: thyms/anbu-presentation-stubulator
    branch: develop
