script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: oJREkaREydM5jOTVranDR20wamyn/gwHFGVcC9gPO1KcYwurXuq9sPTjfIKL0+qpptkHRIV67gG+sQppfA0qxASfhofFI/KoWT4nrN9s/k/vJD5eSzHg93uEg5TedwmJFvOOmMPA3Rpi4p76+RKNEX8sWV35/kv4uolfQhPJ464=
  app:
    develop: anbu-presentation-stub01
