script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: PrsLjtS1kuRelPGsjEAHckZyUiIJeuD0WuV7rk87YEyw8o7ym8kKRPaMvNVlyQrW4Sc5ZIRkTuGK83WXAw7WPZ6RclQAQVxIzLOCBV5+IvBambr6BKoUzfUp7iVbj2IFbbGO5lNA19OW+D8/Kcx3z71HAXkQJkBDRutu8FB23/s=
  app:
    develop: anbu-presentation-stub01
